---
title: "assignment3"
author: "AJ Fowler"
date: "2/3/2020"
output: 
  md_document:
    variant: markdown_github
---
```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

c("ggplot2",
  "purrr",
  "devtools",
  "dplyr",
  "stringr",
  "forcats",
  "gapminder"      
  ) -> package_names  
for(package_name in package_names) {
  if(!is.element(package_name, installed.packages()[,1])) {
     install.packages(package_name,
                      repos = "http://cran.mtu.edu/")
  }
  library(package_name, character.only=TRUE,
          quietly=TRUE,verbose=FALSE)
}

rm(list=c("package_name", "package_names")) 

options(show.signif.stars = FALSE)  
```

```{r}
data.table::fread("./o-ring-erosion-or-blowby.data") -> ring.data

# The space shuttle crashed landed but there were concerns before the flight that they shouldn't fly the shuttle. They didnt do a good job of data visualization and relaying their point so our job is to give god visualization of why they should fly.

ggplot(ring.data, aes(x = TEMPORDFLIGT, y = THERMALDIS, size = LAUNCHTEMP))+
  geom_point() +
  xlab("Temporal order of flight")+
  ylab("# of O-Rings experiencing thermal distress")
  ggtitle("Number of O-rings at risk", subtitle = "Number of O-rings that will experience thermal distress for a given flight when the launch temperature is below freezing")

# The cause of the disaster was traced to an O-ring, a circular gasket that sealed the right rocket booster. This had failed due to the low temperature (31°F / -0.5°C) at launch time – a risk that several engineers noted, but that NASA management dismissed. 

```

